Dz4 calendar
js-tasks-ru/htmlcss-20210513_ilnara-19 pull request #10
Opened 2021-06-02 14:33 UTC by Ilnara-19

2021-06-02 14:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-02 14:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-07 08:33 UTC, GSemikozov requested changes

2021-06-07 08:33 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +span {
стили для span и body следует вынести из файла компонента .calendar

2021-06-07 08:33 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  color: #334D6E;
цвет, по идее, можем забрать из переменных

2021-06-07 08:33 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  margin: 0 53px 24px 58px;
можно ограничиться `margin-bottom: 24px` и `text-align: center` ;)

2021-06-09 13:47 UTC, Ilnara-19 commented on 05-lection3/03-calendar/calendar.css
> +span {
перенесла в общий файл

2021-06-09 13:47 UTC, Ilnara-19 commented on 05-lection3/03-calendar/calendar.css
> +  color: #334D6E;
цвет добавила, как переменную

2021-06-09 13:48 UTC, Ilnara-19 commented on 05-lection3/03-calendar/calendar.css
> +  margin: 0 53px 24px 58px;
логично, убрала лишние отступы

2021-06-09 16:01 UTC, GSemikozov approved these changes

2021-06-09 16:01 UTC, merged