Dz5 avatar
js-tasks-ru/htmlcss-20210513_ilnara-19 pull request #11
Opened 2021-06-02 15:36 UTC by Ilnara-19

Немного не разобралась с srcset, так и не поняла должна ли переключаться картинка при изменение разрешения экрана. Во вкладке network картинка так и не менялась

2021-06-02 15:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-02 15:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-02 16:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-03 15:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-07 08:21 UTC, GSemikozov commented
> Немного не разобралась с srcset, так и не поняла должна ли переключаться картинка при изменение разрешения экрана. Во вкладке network картинка так и не менялась

она поменяется только при изменении экрана (точнее, плотности пикселей экрана)

2021-06-07 08:30 UTC, GSemikozov requested changes

2021-06-07 08:30 UTC, GSemikozov commented on 06-lection4/03-srcset/index.html
> +        <img class="img" src="./public/forest_400.jpg" srcset= "./public/forest_768.jpg 2x"  alt="forest">
чтобы дать выбор браузеру, все-таки в srcset стоит указать и 1x - `srcset= "./public/forest_400.jpg 1x, ./public/forest_768.jpg 2x"`

2021-06-07 08:30 UTC, GSemikozov commented on 06-lection4/01-avatar/index.html
> +      <img class="avatar avatar--main avatar--skeleton avatar--large" src="./public/avatar-200.jpg" alt="avatar" >
если --large и --skeleton не используем, лучше сразу удалить)

2021-06-09 14:21 UTC, Ilnara-19 commented on 06-lection4/03-srcset/index.html
> +        <img class="img" src="./public/forest_400.jpg" srcset= "./public/forest_768.jpg 2x"  alt="forest">
эту часть исправила

2021-06-09 14:21 UTC, Ilnara-19 commented on 06-lection4/01-avatar/index.html
> +      <img class="avatar avatar--main avatar--skeleton avatar--large" src="./public/avatar-200.jpg" alt="avatar" >
--large удалила, но второй оставила, хочу потом его добавить в скелетон

2021-06-09 16:02 UTC, GSemikozov approved these changes

2021-06-09 16:02 UTC, merged