Tooltip
js-tasks-ru/htmlcss-20210513_ilnara-19 pull request #14
Opened 2021-06-13 14:37 UTC by Ilnara-19

2021-06-13 14:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-16 17:35 UTC, GSemikozov requested changes

2021-06-16 17:35 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  display: flex;
лучше все-таки display: inline-flex - иначе если мы захотим добавить иконку с тултипом где-нибудь рядом с текстом - у нас это не получится, поскольку .tooltip у нас блочный

2021-06-16 17:35 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  margin-top: 12px;
мне кажется тут не должно быть внешних отступов, иначе они будут влиять на позиционирование всплывающего блока

2021-06-18 14:16 UTC, Ilnara-19 commented on 05-lection3/01-tooltip/tooltip.css
> +  margin-top: 12px;
каким способом влиять? не совсем это пока представляю. Добавила у .tooltip__answer {
  margin-bottom: 12px;}

2021-06-18 14:16 UTC, Ilnara-19 commented on 05-lection3/01-tooltip/tooltip.css
> +  display: flex;
исправила

2021-06-18 15:30 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  margin-top: 12px;
в данном случае марджин мы используем для правильного позиционирования всплывающей подсказки с учетом стрелки, верно? если так, то ради такой цели надежнее использовать внутренние свойства самой всплывающей подсказки (тот же transform: translate) и не привязываться к внешним отступам других элементов)

2021-06-18 15:31 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  margin-top: 12px;
в данном случае марджин мы используем для правильного позиционирования всплывающей подсказки с учетом стрелки, верно? если так, то ради такой цели надежнее использовать внутренние свойства самой всплывающей подсказки (тот же transform: translate) и не привязываться к внешним отступам других элементов)

2021-06-19 13:42 UTC, Ilnara-19 commented on 05-lection3/01-tooltip/tooltip.css
> +  margin-top: 12px;
я поправила, но такой марджин лучше не делать, так как по сути подсказка+стрелка+иконка вопроса являются один блоком, но из-за того что стрелка идет отдельным слоем, то лучше марджин не писать, а писать transform: translate, так?

2021-06-19 19:16 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  margin-top: 12px;
тут логика лишь в том, что марджин - это внешний отступ, соответственно, он должен использоваться чтобы передвинуть элемент относительно других элементов. Но - в нашем случае всплывающая подсказка имеет абсолютное позиционирование, поэтому марджин у иконки ни от чего ее не отталкивает)

2021-06-20 14:17 UTC, GSemikozov approved these changes

2021-06-20 14:18 UTC, merged