Modal
js-tasks-ru/htmlcss-20210513_ilnara-19 pull request #15
Opened 2021-06-14 05:27 UTC by Ilnara-19

2021-06-14 05:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-14 05:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-15 10:31 UTC, GSemikozov requested changes

2021-06-15 10:31 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  top: -80%;
тут лучше все-таки в пикселях, чтобы не зависеть от чего-либо и чтобы отступ всегда был одинаковый

2021-06-16 15:20 UTC, Ilnara-19 commented on 05-lection3/02-modal/modal.css
> +  top: -80%;
исправила на px

2021-06-16 17:35 UTC, GSemikozov approved these changes

2021-06-16 17:35 UTC, merged