checkbox
js-tasks-ru/htmlcss-20210513_ilnara-19 pull request #16
Opened 2021-06-14 09:53 UTC by Ilnara-19

2021-06-14 09:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-15 09:14 UTC, GSemikozov requested changes

2021-06-15 09:14 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +  opacity: .5;
как и в случае с кнопками - советую при disabled запрещать пользователю взаимодействовать с элементов через `pointer-events: none`

2021-06-16 15:39 UTC, Ilnara-19 commented on 07-lection5/01-checkbox/checkbox.css
> +  opacity: .5;
добавила

2021-06-16 17:36 UTC, GSemikozov approved these changes

2021-06-16 17:36 UTC, merged