radio button
js-tasks-ru/htmlcss-20210513_ilnara-19 pull request #17
Opened 2021-06-14 14:49 UTC by Ilnara-19

2021-06-14 14:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-14 14:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-14 14:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-15 09:21 UTC, GSemikozov requested changes

2021-06-15 09:21 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +  margin-bottom: 16px;
этот марджин нам точно потребуется при любом использовании радио кнопки? если да - то коммент можно зарезолвить)

2021-06-15 09:21 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +  opacity: .5;
писал в предыдущем ПР

2021-06-15 09:21 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +  border: 2px solid var(--blue-2);
на всякий случай советую проверить что у .radio__control `box-sizing: border-box`, иначе при увеличении бордера на 1px и ширина / ввысота элемента тоже может увеличиться)

2021-06-16 15:47 UTC, Ilnara-19 commented on 07-lection5/02-radio/radio.css
> +  margin-bottom: 16px;
нет, не нужен он, у меня такой же margin у toggler, наверное его лучше вообще убрать, но ничего что все они прилипнут друг к другу? или можно потом margin через модификатор добавить, когда используем например на какой-то странице?

2021-06-16 16:20 UTC, Ilnara-19 commented on 07-lection5/02-radio/radio.css
> +  margin-bottom: 16px;
в итоге убрала margin и добавила через модификатор radio__state-margin, так правильно делать?

2021-06-16 16:21 UTC, Ilnara-19 commented on 07-lection5/02-radio/radio.css
> +  opacity: .5;
добавила

2021-06-16 16:23 UTC, Ilnara-19 commented on 07-lection5/02-radio/radio.css
> +  border: 2px solid var(--blue-2);
я прописала для всех элементов в main.css box-sizing: border-box

2021-06-16 16:42 UTC, Ilnara-19 commented on 07-lection5/02-radio/radio.css
> +  margin-bottom: 16px;
или лучше все таки еще обертку сделать и у него марджин прописать?

2021-06-18 14:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-18 14:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-18 14:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-18 15:37 UTC, GSemikozov requested changes

2021-06-18 15:37 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +  margin-bottom: 16px;
поскольку `__state` - это элемент, ему корректно задавать внешние отступы, я просто уточнил везде ли нужен такой отступ (везде где используются эти радио кнопки) =)
так что переделывать в модификатор не обязательно.
но я бы на самом деле лучше задавал margin-bottom на самом блоке - .radio, но - через микс (еще один плюс микса - через родителя можно будет определить последний элемент в списке и убрать у него ненужный отступ снизу)

2021-06-19 13:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-22 21:21 UTC, GSemikozov requested changes

2021-06-22 21:21 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +  margin-bottom: 16px;
https://codepen.io/hermansemykozov/pen/BaWEzxQ?editors=1100

2021-06-22 21:24 UTC, GSemikozov requested changes

2021-06-22 21:24 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radio-group {
все правильно, единственное - надо вынести стили для .radio-group в отдельный файл стилей - поскольку это отдельный блок и он не относится к собственно блоку .radio

2021-06-25 09:44 UTC, Ilnara-19 commented on 07-lection5/02-radio/radio.css
> +.radio-group {
вынесла

2021-06-25 18:22 UTC, GSemikozov approved these changes

2021-06-25 18:22 UTC, merged