Field
js-tasks-ru/htmlcss-20210513_ilnara-19 pull request #19
Opened 2021-06-15 04:54 UTC by Ilnara-19

2021-06-15 04:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-15 10:27 UTC, GSemikozov requested changes

2021-06-15 10:27 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  width: 350px;
ширину пожалуй не стоит столь жестко ограничивать, будет проблема на мобилках)

2021-06-15 10:27 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  padding-left: 24px;
справа тоже нужен отступ, поэтому можно записать в короткой форме `padding: ...`

2021-06-15 10:27 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  outline: none;
и еще бы добавить appearance: none чтобы избежать отрисовки браузером нежелательных элементов

2021-06-15 10:27 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  font-family: "Inter", sans-serif;
можно не указывать, отнаследуется от родителя)

2021-06-15 10:27 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  transform: translate(-150%, -50%);
а справа при checked иконка точно будет right: 2px (или сколько по дизайну)? если мы трансформируем в процентах

2021-06-16 15:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-16 15:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-16 15:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-16 16:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-16 16:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-16 16:50 UTC, Ilnara-19 commented on 07-lection5/04-input/input.css
> +  width: 350px;
написала width: 100%

2021-06-16 16:50 UTC, Ilnara-19 commented on 07-lection5/04-input/input.css
> +  padding-left: 24px;
написала

2021-06-16 16:50 UTC, Ilnara-19 commented on 07-lection5/04-input/input.css
> +  outline: none;
добавила

2021-06-16 17:13 UTC, Ilnara-19 commented on 07-lection5/04-input/input.css
> +  transform: translate(-150%, -50%);
поправила на right: 10px

2021-06-16 17:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-16 17:37 UTC, GSemikozov approved these changes

2021-06-16 17:37 UTC, merged