Mobail menu
js-tasks-ru/htmlcss-20210513_ilnara-19 pull request #23
Opened 2021-07-09 04:46 UTC by Ilnara-19

2021-07-09 04:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-12 07:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-12 09:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-12 09:50 UTC, GSemikozov requested changes

2021-07-12 09:50 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  display: flex;
его еще надо спозиционировать относительно окна браузера - то есть position: fixed

2021-07-12 09:50 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.active {
здесь и ниже .active висит как самостоятельный класс-блок, надо бы перевести его в БЭМ чтобы понимать к чему он относится)

2021-07-12 09:50 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +div [data-open] {
все-таки не любой div на странице, а конкретный блок - то есть .burger, и пробел между классом блока и [data-open] надо убрать (мы ведь проверяем есть ли именно у блока этот атрибут)

2021-07-13 10:44 UTC, Ilnara-19 commented on 09-lection7/01-burger-menu/burger-menu.css
> +  display: flex;
поправила

2021-07-13 10:45 UTC, Ilnara-19 commented on 09-lection7/01-burger-menu/burger-menu.css
> +.active {
поправила

2021-07-13 10:46 UTC, Ilnara-19 commented on 09-lection7/01-burger-menu/burger-menu.css
> +div [data-open] {
поправила

2021-07-13 10:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-13 11:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-13 12:56 UTC, GSemikozov requested changes

2021-07-13 12:56 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  display: flex;
но наверно не запушено)

2021-07-17 07:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-17 08:01 UTC, GSemikozov approved these changes

2021-07-17 08:01 UTC, merged