media page
js-tasks-ru/htmlcss-20210513_ilnara-19 pull request #24
Opened 2021-07-27 15:01 UTC by Ilnara-19

2021-07-27 15:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-08 12:01 UTC, GSemikozov requested changes

2021-08-08 12:01 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@media (max-width: 575px) {
нет смысла дублировать, мы уже чуть выше определили что для экранов шириной 768 и нижу ширина будет вычисляться по внутреннему содержимому кнопки

2021-08-08 12:01 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    width: inherit;
если наследуемся от width: 100%; то это не обязательно явно указывать)

2021-08-08 12:01 UTC, GSemikozov commented on components/footer/footer.css
> +    font-size: 28px;
чуть выше уже определили для экранов с такой шиориной

2021-08-08 12:01 UTC, GSemikozov commented on components/header/header.css
> +  padding-left: 57px;
точно ли это надо? не совсем понятно для чего такой отступ слева

2021-08-09 06:41 UTC, Ilnara-19 commented on 03-lection1/01-button/button.css
> +@media (max-width: 575px) {
тут поправила

2021-08-09 06:43 UTC, Ilnara-19 commented on 07-lection5/04-input/input.css
> +    width: inherit;
указала width: 100%, чтобы .input--small переписать в медиа

2021-08-09 06:44 UTC, Ilnara-19 commented on components/footer/footer.css
> +    font-size: 28px;
убрала лишнее

2021-08-09 06:48 UTC, Ilnara-19 commented on components/header/header.css
> +  padding-left: 57px;
в макете такой был, но убрала вообще отступ и вроде без него хорошо смотрится

2021-08-09 08:08 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    width: inherit;
я к тому что выше ведь уже задали  input { width: 100% } ;)

2021-08-09 08:17 UTC, GSemikozov approved these changes

2021-08-09 08:17 UTC, merged