Dz2 accordion
js-tasks-ru/htmlcss-20210513_ilnara-19 pull request #3
Opened 2021-05-25 15:10 UTC by Ilnara-19

2021-05-25 15:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-26 14:49 UTC, GSemikozov requested changes

2021-05-26 14:49 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +h1 {
сброс стилей надо собрать где-то в одном месте, чтобы они отрабатывали глобально (например, в том же main.css или normalize). Кроме того - в файле стилей блока должны быть стили только для блока и его элементов и модификаторов)

2021-05-26 14:49 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details summary::-webkit-details-marker {
то же самое касается details и summary. Если же мы делаем сброс в контексте блока - тогда нужно использовать соответствующие семантические БЭМ-классы - accordion__item и accordion__header

2021-05-26 14:49 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.section__inner {
и снова - section делает разметку которая определяет внешнее поведение аккордиона, поэтому эти стили надо вынести либо в отдельный файл стилей, либо добавить на страницу решения ДЗ прямо в тег style - пусть болтаются там, мы их переиспользовать не будем, они специфичны для данного конкретного случая.

2021-05-26 14:49 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  margin-top: 75px;
у блока не стоит задавать внешние отступы, иначе такой блок будет проблематично встраивать в различные контексты (где-то эти отступы ок, а где-то - испортят всю картину, придется переопределять). Внешнее поведение, напомню, задаем через родителя или его элементы (в виде миксов) ;)

2021-05-26 14:49 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding-bottom: 32px;
на самом деле здесь и в accordion__header padding-right тоже стоит указывать - на случай если текст будет слишком длинным

2021-05-26 14:49 UTC, GSemikozov commented on components/page/page.css
> +body {
в этом файле собраны все стили которые касаются страницы, но - мы все-таки используем модульный подход, поэтому в папке `components/page/page.css` должны быть стили которые касаются лишь блока `.page`, остальные стили надо определить в других блоках (`.card, .footer`) либо на уровне сброса стилей (body, h и пр.)

2021-06-04 08:29 UTC, Ilnara-19 commented on 03-lection1/02-accordion/accordion.css
> +h1 {
Сделала сброс в main.css

2021-06-04 08:29 UTC, Ilnara-19 commented on 03-lection1/02-accordion/accordion.css
> +details summary::-webkit-details-marker {
Вынесла в общий файл main.css

2021-06-04 08:30 UTC, Ilnara-19 commented on 03-lection1/02-accordion/accordion.css
> +.section__inner {
Вынесла в style

2021-06-04 08:30 UTC, Ilnara-19 commented on 03-lection1/02-accordion/accordion.css
> +  margin-top: 75px;
Да , переделала, в БЭМ об этом прочла

2021-06-04 08:30 UTC, Ilnara-19 commented on 03-lection1/02-accordion/accordion.css
> +  padding-bottom: 32px;
Указала

2021-06-04 08:31 UTC, Ilnara-19 commented on components/page/page.css
> +body {
Переместила блоки в отдельные .CSS и подключила их в .html файл главной страницы

2021-06-07 08:30 UTC, GSemikozov requested changes

2021-06-07 08:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding-top: 75px;
паддинги лучше добавить через родителя например section__accordion, а отсюда - убрать, иначе если мы вставим такой аккордион в проект - появятся ненужные огромные отступы)) 
кстати, когда будем добавлять аккордион в карточку - достаточно добавить одну секцию, и по умолчанию сделать открытым

2021-06-07 13:46 UTC, Ilnara-19 commented on 03-lection1/02-accordion/accordion.css
> +  padding-top: 75px;
да, все поправила. поняла почему так нужно было переделать

2021-06-07 16:27 UTC, GSemikozov approved these changes

2021-06-07 16:27 UTC, merged