Dz3 skeleton
js-tasks-ru/htmlcss-20210513_ilnara-19 pull request #9
Opened 2021-06-02 14:33 UTC by Ilnara-19

2021-06-02 14:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-07 08:29 UTC, GSemikozov requested changes

2021-06-07 08:29 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__text--width {
не совсем читабельный модификатор, лучше задать более семантический класс, по смыслу того что делает модификатор, например `.skeleton__text--short` | `.skeleton__text--long`

2021-06-07 08:29 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__row {
вообще, я бы посоветовал объединить .skeleton__text и .skeleton__row - пусть это будет .skeleton__line. А выравнивание и размеры можно задавать через модификаторы

2021-06-07 14:53 UTC, Ilnara-19 commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__text--width {
изменила название

2021-06-07 14:53 UTC, Ilnara-19 commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__row {
да, логично, исправила у себя

2021-06-09 11:49 UTC, GSemikozov approved these changes

2021-06-09 11:49 UTC, merged